app = "vaultwarden-webdav"
primary_region = "sin"

[build]
image = "ghcr.io/workerspages/vaultwarden-webdav:latest"

[env]
TZ = "Asia/Shanghai"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 1
processes = [ "app" ]

[[mounts]]
destination = "/data"
source = "vw_data"

[[vm]]
cpus = 1
memory = "256mb"
memory_mb = 256
