app = "xctg"  # 应用名称
primary_region = "hkg"  # 数据中心，比如 hkg、nrt、sin

[build]
  image = "eooce/nodejs:latest"  # 镜像地址

[env]
  NAME = "Fly"  
  NEZHA_SERVER = ""
  NEZHA_PORT = ""
  NEZHA_KEY = ""
  ARGO_DOMAIN = "fly.wgx.qzz.io"
  ARGO_AUTH = "eyJhIjoiNjY1ZWNmMGQwYWY0ZWE3ZmJlNWRhYzQ2NWY3ZTBkZjMiLCJ0IjoiMDczOThhNTMtZDE5OS00MjlkLWEwZjItMWU5ZjQ4ZDliOTBmIiwicyI6Ik9UaGtaV1V6T0RrdE1EWTFOQzAwWldZd0xUazVabU10TlRVNVltWmxORGN6WTJVdyJ9"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = 256
  swap_size_mb = 512
